syntax enable
filetype plugin indent on
set hidden
set number
set relativenumber
set autoread
set noerrorbells visualbell t_vb=
set noswapfile
set nobackup
set nowritebackup
set undofile
set hlsearch
set incsearch
set ignorecase
set smartcase
set autoindent
set smarttab
set linebreak
set tabstop=2
set shiftwidth=2
set softtabstop=2
set updatetime=100
set clipboard=unnamedplus
set viminfo='50,f1,<500,n~/.config/vim/viminfo
runtime! ftplugin/man.vim
au FocusGained,BufEnter * silent! checktime
