os:
  editPreset: "nvim"
  openDirInEditor: "nvim +Oil"

  # Config relating to git
git:
  # See https://github.com/jesseduffield/lazygit/blob/master/docs/Custom_Pagers.md
  paging:
    colorArg: always

  commit: # If true, pass '--signoff' flag when committing
    signOff: true
    autoWrapCommitMessage: true
    autoWrapWidth: 72

  merging: # If true, run merges in a subprocess so that if a commit message is required, Lazygit will not hang Only applicable to unix users.
    manualCommit: false
    args: "" # Extra args passed to `git merge`, e.g. --no-ff
    squashMergeMessage: Squash merge {{selectedRef}} into {{currentBranch}}

  mainBranches:
    - master
    - main
  skipHookPrefix: WIP
  autoFetch: true
  autoRefresh: true
  fetchAll: true
  autoStageResolvedConflicts: true
  branchLogCmd: git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium {{branchName}} --
  allBranchesLogCmd: git log --graph --all --color=always --abbrev-commit --decorate --date=relative  --pretty=medium
  disableForcePushing: true

  branchPrefix: "" # See https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#predefined-branch-name-prefix

  parseEmoji: true # If true, parse emoji strings in commit messages e.g. render :rocket: as 🚀

update: # One of: 'prompt' (default) | 'background' | 'never'
  method: prompt

  days: 14 # Period in days between update checks

refresher: # Background refreshes
  refreshInterval: 10
  fetchInterval: 60

confirmOnQuit: true # If true, show a confirmation popup before quitting Lazygit
quitOnTopLevelReturn: false
disableStartupPopups: false

notARepository: skip # What to do when opening Lazygit outside of a git repo. - 'prompt': (default) ask whether to initialize a new repo or open in the most recent repo - 'create': initialize a new repo - 'skip': open most recent repo - 'quit': exit Lazygit If true, display a confirmation when subprocess terminates. This allows you to view the output of the subprocess before returning to Lazygit.
promptToReturnFromSubprocess: false
